-- ============================================================================
-- Queens' Touch — PostgreSQL schema (executable blueprint)
-- Target: PostgreSQL 18. Run: psql -U <user> -d <dbname> -f database/schema.sql
--
-- Decisions:
--  * UUID primary keys, generated by the backend on insert.
--  * Products/categories/brands are soft-deactivated (status / is_active), never
--    destroyed, so historical orders stay intact.
--  * Stock lives on product_variants.stock_qty; inventory_transactions records
--    the full adjustment/order history. Low-stock/out-of-stock are derived from
--    variant stock vs products.stock_threshold.
--  * Enums constrain statuses. CHECK constraints guard negative quantities/prices.
-- ============================================================================

CREATE TABLE roles (
  id          UUID PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE permissions (
  id          UUID PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  description TEXT
);

CREATE TABLE role_permissions (
  role_id       UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
  id            UUID PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  phone         TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  role_id       UUID NOT NULL REFERENCES roles(id),
  password_hash TEXT,
  avatar_url    TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_role ON users(role_id);

CREATE TABLE categories (
  id          UUID PRIMARY KEY,
  parent_id   UUID REFERENCES categories(id),
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url   TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_categories_parent ON categories(parent_id);

CREATE TABLE brands (
  id         UUID PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  slug       TEXT NOT NULL UNIQUE,
  logo_url   TEXT,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TYPE product_status AS ENUM ('active', 'inactive', 'discontinued');

CREATE TABLE products (
  id              UUID PRIMARY KEY,
  name            TEXT NOT NULL,
  slug            TEXT NOT NULL UNIQUE,
  description     TEXT NOT NULL DEFAULT '',
  category_id     UUID NOT NULL REFERENCES categories(id),
  brand_id        UUID NOT NULL REFERENCES brands(id),
  base_price      NUMERIC(10,2) NOT NULL CHECK (base_price >= 0),
  discount_price  NUMERIC(10,2) CHECK (discount_price IS NULL OR (discount_price >= 0 AND discount_price < base_price)),
  stock_threshold INTEGER NOT NULL DEFAULT 5 CHECK (stock_threshold >= 0),
  status          product_status NOT NULL DEFAULT 'active',
  rating          NUMERIC(3,2) NOT NULL DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
  review_count    INTEGER NOT NULL DEFAULT 0 CHECK (review_count >= 0),
  sold_count      INTEGER NOT NULL DEFAULT 0 CHECK (sold_count >= 0),
  view_count      INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  is_featured     BOOLEAN NOT NULL DEFAULT FALSE,
  is_new_arrival  BOOLEAN NOT NULL DEFAULT FALSE,
  is_best_seller  BOOLEAN NOT NULL DEFAULT FALSE,
  is_trending     BOOLEAN NOT NULL DEFAULT FALSE,
  specifications  JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_brand ON products(brand_id);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_created ON products(created_at DESC);

CREATE TABLE product_variants (
  id         UUID PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  sku        TEXT NOT NULL UNIQUE,
  size       TEXT,
  color      TEXT,
  shade      TEXT,
  price      NUMERIC(10,2) CHECK (price IS NULL OR price >= 0),
  stock_qty  INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  is_active  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (size IS NOT NULL OR color IS NOT NULL OR shade IS NOT NULL)
);

CREATE INDEX idx_variants_product ON product_variants(product_id);
CREATE INDEX idx_variants_sku ON product_variants(sku);

CREATE TABLE product_images (
  id         UUID PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  url        TEXT NOT NULL,
  position   INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (product_id, position)
);

CREATE INDEX idx_product_images_product ON product_images(product_id);

-- ============================ commerce ======================================

CREATE TYPE payment_method AS ENUM ('cash_on_delivery', 'bank_transfer', 'paybill', 'card', 'installment');
CREATE TYPE payment_status AS ENUM ('pending', 'pending_verification', 'successful', 'partially_paid', 'failed', 'refunded', 'rejected');
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'processing', 'ready', 'delivered', 'cancelled');

CREATE TABLE carts (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_items (
  id         UUID PRIMARY KEY,
  cart_id    UUID NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id),
  variant_id UUID REFERENCES product_variants(id),
  quantity   INTEGER NOT NULL CHECK (quantity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (cart_id, product_id, variant_id)
);

CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);
-- NULL variant_id is treated as distinct by unique indexes, so rows for the
-- same (cart, product) without a variant could be duplicated. This closes that gap.
CREATE UNIQUE INDEX idx_cart_items_cart_product_no_variant
  ON cart_items(cart_id, product_id) WHERE variant_id IS NULL;

CREATE TABLE wishlists (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE wishlist_items (
  id          UUID PRIMARY KEY,
  wishlist_id UUID NOT NULL REFERENCES wishlists(id) ON DELETE CASCADE,
  product_id  UUID NOT NULL REFERENCES products(id),
  added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (wishlist_id, product_id)
);

CREATE INDEX idx_wishlist_items_wishlist ON wishlist_items(wishlist_id);

CREATE TABLE addresses (
  id         UUID PRIMARY KEY,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label      TEXT NOT NULL DEFAULT 'Home',
  full_name  TEXT NOT NULL,
  phone      TEXT NOT NULL,
  street     TEXT NOT NULL,
  city       TEXT NOT NULL,
  state      TEXT NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_addresses_user ON addresses(user_id);

CREATE TYPE promotion_type AS ENUM ('percentage', 'fixed');

CREATE TABLE promotions (
  id                   UUID PRIMARY KEY,
  code                 TEXT NOT NULL UNIQUE,
  title                TEXT NOT NULL,
  description          TEXT,
  type                 promotion_type NOT NULL,
  value                NUMERIC(10,2) NOT NULL,
  category_id          UUID REFERENCES categories(id),
  product_id           UUID REFERENCES products(id),
  minimum_order_amount NUMERIC(10,2) CHECK (minimum_order_amount IS NULL OR minimum_order_amount > 0),
  maximum_discount     NUMERIC(10,2) CHECK (maximum_discount IS NULL OR maximum_discount > 0),
  usage_limit          INTEGER CHECK (usage_limit IS NULL OR usage_limit > 0),
  usage_count          INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  start_date           TIMESTAMPTZ,
  end_date             TIMESTAMPTZ,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (NOT (type = 'percentage' AND value > 100)),
  CHECK (NOT (type = 'fixed' AND value <= 0)),
  CHECK (end_date IS NULL OR start_date IS NULL OR end_date > start_date)
);

CREATE INDEX idx_promotions_code ON promotions(code);

CREATE TABLE orders (
  id                    UUID PRIMARY KEY,
  order_number          TEXT NOT NULL UNIQUE,
  customer_id           UUID NOT NULL REFERENCES users(id),
  customer_name         TEXT NOT NULL,
  customer_phone        TEXT NOT NULL,
  customer_email        TEXT NOT NULL,
  shipping_address      TEXT NOT NULL,
  subtotal              NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
  discount              NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  shipping_fee          NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
  total                 NUMERIC(10,2) NOT NULL CHECK (total >= 0),
  status                order_status NOT NULL DEFAULT 'pending',
  payment_status        payment_status NOT NULL DEFAULT 'pending',
  payment_method        payment_method NOT NULL,
  installment_requested BOOLEAN NOT NULL DEFAULT FALSE,
  promotion_code        TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (total = subtotal - discount + shipping_fee)
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

CREATE TABLE order_items (
  id            UUID PRIMARY KEY,
  order_id      UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id    UUID NOT NULL REFERENCES products(id),
  variant_id    UUID REFERENCES product_variants(id),
  product_name  TEXT NOT NULL,
  variant_label TEXT,
  unit_price    NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  line_total    NUMERIC(10,2) NOT NULL CHECK (line_total >= 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (line_total = unit_price * quantity)
);

CREATE INDEX idx_order_items_order ON order_items(order_id);

CREATE TABLE payments (
  id                    UUID PRIMARY KEY,
  order_id              UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  customer_id           UUID NOT NULL REFERENCES users(id),
  amount                NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  method                payment_method NOT NULL,
  status                payment_status NOT NULL DEFAULT 'pending',
  reference             TEXT,
  payment_date          DATE,
  confirmation_message  TEXT,
  note                  TEXT,
  verified_at           TIMESTAMPTZ,
  verified_by           UUID REFERENCES users(id),
  rejected_at           TIMESTAMPTZ,
  rejected_by           UUID REFERENCES users(id),
  reject_reason         TEXT,
  duplicate_of          UUID REFERENCES payments(id),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_customer ON payments(customer_id);

CREATE TYPE installment_status AS ENUM ('pending_approval', 'approved', 'active', 'completed', 'rejected', 'overdue');

CREATE TABLE installments (
  id          UUID PRIMARY KEY,
  order_id    UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES users(id),
  total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount > 0),
  amount_paid NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0 AND amount_paid <= total_amount),
  term_months INTEGER NOT NULL DEFAULT 3 CHECK (term_months >= 2 AND term_months <= 12),
  status      installment_status NOT NULL DEFAULT 'pending_approval',
  approved_by UUID REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  rejected_by UUID REFERENCES users(id),
  rejected_at TIMESTAMPTZ,
  reject_reason TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_installments_order ON installments(order_id);
CREATE INDEX idx_installments_customer ON installments(customer_id);

CREATE TABLE installment_payments (
  id            UUID PRIMARY KEY,
  installment_id UUID NOT NULL REFERENCES installments(id) ON DELETE CASCADE,
  amount        NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  due_date      DATE NOT NULL,
  paid_at       TIMESTAMPTZ,
  is_paid       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (is_paid = (paid_at IS NOT NULL))
);

CREATE INDEX idx_installment_payments_installment ON installment_payments(installment_id);

-- ============================ engagement & ops ==============================

CREATE TABLE reviews (
  id                   UUID PRIMARY KEY,
  product_id           UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  customer_id          UUID NOT NULL REFERENCES users(id),
  order_id             UUID REFERENCES orders(id),
  rating               NUMERIC(2,1) NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment              TEXT NOT NULL DEFAULT '',
  is_verified_purchase BOOLEAN NOT NULL DEFAULT FALSE,
  is_approved          BOOLEAN NOT NULL DEFAULT FALSE,
  is_rejected          BOOLEAN NOT NULL DEFAULT FALSE,
  is_reported          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, customer_id)
);

CREATE INDEX idx_reviews_product ON reviews(product_id);
CREATE INDEX idx_reviews_customer ON reviews(customer_id);

CREATE TYPE notification_type AS ENUM ('account', 'order', 'payment', 'installment', 'promotion', 'announcement');

CREATE TABLE notifications (
  id         UUID PRIMARY KEY,
  user_id    UUID REFERENCES users(id) ON DELETE CASCADE,
  type       notification_type NOT NULL,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL,
  is_read    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_created ON notifications(created_at DESC);

CREATE TYPE audit_action AS ENUM ('create', 'update', 'delete', 'approve', 'reject', 'adjust', 'login', 'logout');

CREATE TABLE audit_logs (
  id             UUID PRIMARY KEY,
  actor_user_id  UUID REFERENCES users(id),
  actor_name     TEXT NOT NULL,
  action         audit_action NOT NULL,
  resource       TEXT NOT NULL,
  resource_id    TEXT,
  description    TEXT NOT NULL,
  previous_value JSONB,
  new_value      JSONB,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_created ON audit_logs(created_at DESC);
CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_user_id);

CREATE TYPE inventory_change_type AS ENUM ('add', 'reduce', 'adjust', 'purchase', 'order');

CREATE TABLE inventory_transactions (
  id                UUID PRIMARY KEY,
  variant_id        UUID NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE,
  product_id        UUID NOT NULL REFERENCES products(id),
  change_type       inventory_change_type NOT NULL,
  quantity_change   INTEGER NOT NULL CHECK (quantity_change <> 0),
  previous_quantity INTEGER NOT NULL CHECK (previous_quantity >= 0),
  new_quantity      INTEGER NOT NULL CHECK (new_quantity >= 0),
  reason            TEXT NOT NULL,
  staff_user_id     UUID REFERENCES users(id),
  order_id          UUID REFERENCES orders(id),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_inv_tx_variant ON inventory_transactions(variant_id);
CREATE INDEX idx_inv_tx_product ON inventory_transactions(product_id);

-- ============================ seed data =====================================

INSERT INTO roles (id, name, description) VALUES
  ('00000000-0000-0000-0000-000000000001', 'super_admin', 'Full administrative access'),
  ('00000000-0000-0000-0000-000000000002', 'store_manager', 'Manages products, orders, customers'),
  ('00000000-0000-0000-0000-000000000003', 'sales_staff', 'Handles orders and payments'),
  ('00000000-0000-0000-0000-000000000004', 'inventory_staff', 'Manages inventory'),
  ('00000000-0000-0000-0000-000000000005', 'customer', 'Storefront customer');

INSERT INTO permissions (id, code, description) VALUES
  ('00000000-0000-0000-0000-000000000101', 'products.read', 'Read products'),
  ('00000000-0000-0000-0000-000000000102', 'products.write', 'Create/update/deactivate products'),
  ('00000000-0000-0000-0000-000000000103', 'inventory.adjust', 'Adjust inventory'),
  ('00000000-0000-0000-0000-000000000104', 'orders.read', 'Read orders'),
  ('00000000-0000-0000-0000-000000000105', 'orders.update', 'Update order status'),
  ('00000000-0000-0000-0000-000000000106', 'payments.manage', 'Manage payments'),
  ('00000000-0000-0000-0000-000000000107', 'installments.manage', 'Manage installments'),
  ('00000000-0000-0000-0000-000000000108', 'customers.read', 'Read customers'),
  ('00000000-0000-0000-0000-000000000109', 'customers.write', 'Write customers'),
  ('00000000-0000-0000-0000-000000000110', 'promotions.manage', 'Manage promotions'),
  ('00000000-0000-0000-0000-000000000111', 'reviews.moderate', 'Moderate reviews'),
  ('00000000-0000-0000-0000-000000000112', 'staff.manage', 'Manage staff'),
  ('00000000-0000-0000-0000-000000000113', 'audit.read', 'Read audit logs');

INSERT INTO role_permissions (role_id, permission_id) VALUES
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000101'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000102'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000103'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000104'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000105'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000106'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000107'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000108'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000109'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000110'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000111'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000112'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000113'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000101'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000102'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000103'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000104'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000105'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000106'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000107'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000108'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000109'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000110'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000111'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000112'),
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000113'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000101'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000104'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000105'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000106'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000107'),
  ('00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000108'),
  ('00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000101'),
  ('00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000103'),
  ('00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000104'),
  ('00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000101');

INSERT INTO users (id, email, phone, full_name, role_id, password_hash) VALUES
  ('00000000-0000-0000-0000-000000000201', 'amara@example.com', '+234 801 234 5678', 'Amara Okafor', '00000000-0000-0000-0000-000000000005', 'scrypt:bd7134e3ecb7b3611a5882060e6a42b2:3f1cbe82425173b1e9a3ae6a6c1ab7fd197474cb5ef576e36f0d05fef8c317e74928b067b8a542f0b447470577fca9bc4550e8aefe675decdbb44987849ad6cb'),
  ('00000000-0000-0000-0000-000000000202', 'admin@queenstouch.com', '+234 802 000 0001', 'Queen Ebele', '00000000-0000-0000-0000-000000000001', 'scrypt:bd7134e3ecb7b3611a5882060e6a42b2:3f1cbe82425173b1e9a3ae6a6c1ab7fd197474cb5ef576e36f0d05fef8c317e74928b067b8a542f0b447470577fca9bc4550e8aefe675decdbb44987849ad6cb'),
  ('00000000-0000-0000-0000-000000000203', 'manager@queenstouch.com', '+234 802 000 0002', 'Sarah Mensah', '00000000-0000-0000-0000-000000000002', 'scrypt:bd7134e3ecb7b3611a5882060e6a42b2:3f1cbe82425173b1e9a3ae6a6c1ab7fd197474cb5ef576e36f0d05fef8c317e74928b067b8a542f0b447470577fca9bc4550e8aefe675decdbb44987849ad6cb'),
  ('00000000-0000-0000-0000-000000000204', 'sales@queenstouch.com', '+234 802 000 0003', 'Doris Achebe', '00000000-0000-0000-0000-000000000003', 'scrypt:bd7134e3ecb7b3611a5882060e6a42b2:3f1cbe82425173b1e9a3ae6a6c1ab7fd197474cb5ef576e36f0d05fef8c317e74928b067b8a542f0b447470577fca9bc4550e8aefe675decdbb44987849ad6cb'),
  ('00000000-0000-0000-0000-000000000205', 'inventory@queenstouch.com', '+234 802 000 0004', 'Chidi Nwosu', '00000000-0000-0000-0000-000000000004', 'scrypt:bd7134e3ecb7b3611a5882060e6a42b2:3f1cbe82425173b1e9a3ae6a6c1ab7fd197474cb5ef576e36f0d05fef8c317e74928b067b8a542f0b447470577fca9bc4550e8aefe675decdbb44987849ad6cb');

INSERT INTO brands (id, name, slug) VALUES
  ('00000000-0000-0000-0000-000000000301', 'Velvet Rose', 'velvet-rose'),
  ('00000000-0000-0000-0000-000000000302', 'Crown & Co', 'crown-co'),
  ('00000000-0000-0000-0000-000000000303', 'Luxé Beaute', 'luxe-beaute'),
  ('00000000-0000-0000-0000-000000000304', 'Maison Élégance', 'maison-elegance'),
  ('00000000-0000-0000-0000-000000000305', 'Silk Garden', 'silk-garden'),
  ('00000000-0000-0000-0000-000000000306', 'Royal Glow', 'royal-glow');

INSERT INTO categories (id, parent_id, name, slug, description) VALUES
  ('00000000-0000-0000-0000-000000000401', NULL, 'Clothing', 'clothing', 'Elegant womenswear for every occasion'),
  ('00000000-0000-0000-0000-000000000402', '00000000-0000-0000-0000-000000000401', 'Dresses', 'clothing-dresses', NULL),
  ('00000000-0000-0000-0000-000000000403', '00000000-0000-0000-0000-000000000401', 'Tops', 'clothing-tops', NULL),
  ('00000000-0000-0000-0000-000000000404', '00000000-0000-0000-0000-000000000401', 'Trousers', 'clothing-trousers', NULL),
  ('00000000-0000-0000-0000-000000000405', '00000000-0000-0000-0000-000000000401', 'Jeans', 'clothing-jeans', NULL),
  ('00000000-0000-0000-0000-000000000406', '00000000-0000-0000-0000-000000000401', 'Skirts', 'clothing-skirts', NULL),
  ('00000000-0000-0000-0000-000000000407', '00000000-0000-0000-0000-000000000401', 'Jackets', 'clothing-jackets', NULL),
  ('00000000-0000-0000-0000-000000000408', '00000000-0000-0000-0000-000000000401', 'Sweaters', 'clothing-sweaters', NULL),
  ('00000000-0000-0000-0000-000000000409', '00000000-0000-0000-0000-000000000401', 'Jumpsuits', 'clothing-jumpsuits', NULL),
  ('00000000-0000-0000-0000-000000000410', '00000000-0000-0000-0000-000000000401', 'Activewear', 'clothing-activewear', NULL),
  ('00000000-0000-0000-0000-000000000411', '00000000-0000-0000-0000-000000000401', 'Loungewear', 'clothing-loungewear', NULL),
  ('00000000-0000-0000-0000-000000000412', NULL, 'Cosmetics & Beauty', 'beauty', 'Makeup, skincare and self-care essentials'),
  ('00000000-0000-0000-0000-000000000413', '00000000-0000-0000-0000-000000000412', 'Makeup', 'beauty-makeup', NULL),
  ('00000000-0000-0000-0000-000000000414', '00000000-0000-0000-0000-000000000412', 'Lip Products', 'beauty-lip', NULL),
  ('00000000-0000-0000-0000-000000000415', '00000000-0000-0000-0000-000000000412', 'Foundation', 'beauty-foundation', NULL),
  ('00000000-0000-0000-0000-000000000416', '00000000-0000-0000-0000-000000000412', 'Concealer', 'beauty-concealer', NULL),
  ('00000000-0000-0000-0000-000000000417', '00000000-0000-0000-0000-000000000412', 'Blush', 'beauty-blush', NULL),
  ('00000000-0000-0000-0000-000000000418', '00000000-0000-0000-0000-000000000412', 'Eyeshadow', 'beauty-eyeshadow', NULL),
  ('00000000-0000-0000-0000-000000000419', '00000000-0000-0000-0000-000000000412', 'Mascara', 'beauty-mascara', NULL),
  ('00000000-0000-0000-0000-000000000420', '00000000-0000-0000-0000-000000000412', 'Skincare', 'beauty-skincare', NULL),
  ('00000000-0000-0000-0000-000000000421', '00000000-0000-0000-0000-000000000412', 'Body Care', 'beauty-body', NULL),
  ('00000000-0000-0000-0000-000000000422', '00000000-0000-0000-0000-000000000412', 'Hair Products', 'beauty-hair', NULL),
  ('00000000-0000-0000-0000-000000000423', '00000000-0000-0000-0000-000000000412', 'Beauty Accessories', 'beauty-accessories', NULL);

INSERT INTO products
  (id, name, slug, description, category_id, brand_id, base_price, discount_price,
   stock_threshold, status, rating, review_count, sold_count, view_count,
   is_featured, is_new_arrival, is_best_seller, is_trending, specifications)
VALUES
  ('00000000-0000-0000-0000-000000000501', 'Rosé Midi Wrap Dress', 'rose-midi-wrap-dress',
   'A timeless midi wrap dress in soft rosé, cut to flatter the waist and flow beautifully.',
   '00000000-0000-0000-0000-000000000402', '00000000-0000-0000-0000-000000000301', 89.99, 69.99, 6, 'active', 4.8, 132, 540, 3200, TRUE, FALSE, TRUE, FALSE,
   '{"Fabric":"Viscose blend","Fit":"True to size","Care":"Hand wash cold"}'),
  ('00000000-0000-0000-0000-000000000502', 'Velvet Blush Blazer', 'velvet-blush-blazer',
   'A soft velvet blazer in blush pink that adds instant polish.',
   '00000000-0000-0000-0000-000000000407', '00000000-0000-0000-0000-000000000302', 129.99, NULL, 5, 'active', 4.6, 64, 210, 1850, TRUE, FALSE, FALSE, TRUE,
   '{"Fabric":"Velvet","Fit":"Relaxed","Care":"Dry clean only"}'),
  ('00000000-0000-0000-0000-000000000503', 'Signature Silk Scarf', 'signature-silk-scarf',
   'An iconic silk scarf with the Queens'' Touch signature pattern.',
   '00000000-0000-0000-0000-000000000423', '00000000-0000-0000-0000-000000000304', 49.99, 39.99, 8, 'active', 4.9, 218, 980, 4100, FALSE, FALSE, TRUE, FALSE,
   '{"Material":"100% silk twill","Size":"90 x 90 cm"}'),
  ('00000000-0000-0000-0000-000000000504', 'Velvet Matte Lipstick - Queen', 'velvet-matte-lipstick-queen',
   'A creamy matte lipstick with full coverage and a velvet finish.',
   '00000000-0000-0000-0000-000000000414', '00000000-0000-0000-0000-000000000303', 24.99, 19.99, 20, 'active', 4.7, 342, 1500, 5200, FALSE, FALSE, TRUE, TRUE,
   '{"Finish":"Matte","Volume":"3.5 g","Cruelty Free":"Yes"}'),
  ('00000000-0000-0000-0000-000000000505', 'Silk Garden Maxi Dress', 'silk-garden-maxi-dress',
   'A flowing maxi dress in a botanical print, cut on the bias.',
   '00000000-0000-0000-0000-000000000402', '00000000-0000-0000-0000-000000000305', 109.99, NULL, 5, 'active', 4.5, 28, 90, 1200, TRUE, TRUE, FALSE, FALSE,
   '{"Fabric":"Silk blend","Fit":"Flowy","Care":"Dry clean"}'),
  ('00000000-0000-0000-0000-000000000506', 'High-Rise Wide-Leg Trousers', 'high-rise-wide-leg-trousers',
   'Crisp tailoring meets comfort in these high-rise wide-leg trousers.',
   '00000000-0000-0000-0000-000000000404', '00000000-0000-0000-0000-000000000302', 74.99, NULL, 6, 'active', 4.4, 85, 320, 1600, FALSE, FALSE, FALSE, TRUE,
   '{"Fabric":"Twill","Fit":"Wide leg","Care":"Machine wash"}'),
  ('00000000-0000-0000-0000-000000000507', 'Luminous Foundation - Medium Tan', 'luminous-foundation-medium-tan',
   'A buildable, luminous foundation that evens tone with a natural glow.',
   '00000000-0000-0000-0000-000000000415', '00000000-0000-0000-0000-000000000303', 39.99, NULL, 15, 'active', 4.6, 189, 760, 2800, TRUE, FALSE, TRUE, FALSE,
   '{"Coverage":"Buildable","Finish":"Luminous","Volume":"30 ml"}'),
  ('00000000-0000-0000-0000-000000000508', 'Hydra Glow Serum', 'hydra-glow-serum',
   'A weightless serum that drenches skin in hydration.',
   '00000000-0000-0000-0000-000000000420', '00000000-0000-0000-0000-000000000306', 34.99, NULL, 12, 'active', 4.9, 156, 620, 3400, FALSE, TRUE, FALSE, TRUE,
   '{"Skin type":"All","Key actives":"Hyaluronic acid, Vitamin C"}'),
  ('00000000-0000-0000-0000-000000000509', 'Corset-Style Jumpsuit', 'corset-style-jumpsuit',
   'A sculpted corset jumpsuit with wide legs and a dramatic flared silhouette.',
   '00000000-0000-0000-0000-000000000409', '00000000-0000-0000-0000-000000000301', 99.99, 79.99, 5, 'active', 4.3, 47, 175, 900, FALSE, FALSE, FALSE, TRUE,
   '{"Fabric":"Crepe","Fit":"Sculpted","Care":"Dry clean"}'),
  ('00000000-0000-0000-0000-000000000510', 'Plush Lounge Set', 'plush-lounge-set',
   'A buttery-soft two-piece lounge set in a cloud-feel knit.',
   '00000000-0000-0000-0000-000000000411', '00000000-0000-0000-0000-000000000305', 59.99, NULL, 8, 'active', 4.7, 39, 140, 1100, FALSE, TRUE, FALSE, FALSE,
   '{"Fabric":"Modal blend","Fit":"Relaxed","Care":"Machine wash"}'),
  ('00000000-0000-0000-0000-000000000511', 'Scalp Detox Hair Mask', 'scalp-detox-hair-mask',
   'A weekly treatment that clarifies the scalp and strengthens strands.',
   '00000000-0000-0000-0000-000000000422', '00000000-0000-0000-0000-000000000306', 29.99, NULL, 10, 'active', 4.5, 71, 290, 1300, FALSE, FALSE, TRUE, FALSE,
   '{"Use":"Weekly","Key actives":"Rosemary, Aloe"}'),
  ('00000000-0000-0000-0000-000000000512', 'Crystal Statement Earrings', 'crystal-statement-earrings',
   'Hand-finished crystal earrings that catch the light with every move.',
   '00000000-0000-0000-0000-000000000423', '00000000-0000-0000-0000-000000000304', 44.99, 34.99, 6, 'active', 4.8, 92, 430, 2400, FALSE, FALSE, FALSE, TRUE,
   '{"Material":"Crystal, gold-plated","Type":"Drop earrings"}'),
  ('00000000-0000-0000-0000-000000000513', 'Everyday Straight-Leg Jeans', 'everyday-straight-leg-jeans',
   'The perfect pair of straight-leg jeans in a rich indigo wash.',
   '00000000-0000-0000-0000-000000000405', '00000000-0000-0000-0000-000000000302', 64.99, NULL, 6, 'active', 4.5, 110, 460, 2000, FALSE, FALSE, TRUE, FALSE,
   '{"Fabric":"Denim with stretch","Rise":"Mid","Care":"Machine wash"}'),
  ('00000000-0000-0000-0000-000000000514', 'Plush Velvet Mascara', 'plush-velvet-mascara',
   'Volumizing mascara with a plush brush that lifts and separates.',
   '00000000-0000-0000-0000-000000000419', '00000000-0000-0000-0000-000000000303', 21.99, NULL, 18, 'active', 4.4, 58, 240, 950, TRUE, FALSE, FALSE, FALSE,
   '{"Finish":"Volumizing","Waterproof":"No","Volume":"10 ml"}'),
  ('00000000-0000-0000-0000-000000000515', 'Chiffon Pleated Skirt', 'chiffon-pleated-skirt',
   'A featherlight pleated chiffon skirt that moves with you.',
   '00000000-0000-0000-0000-000000000406', '00000000-0000-0000-0000-000000000305', 54.99, NULL, 7, 'active', 4.6, 33, 120, 780, FALSE, TRUE, FALSE, FALSE,
   '{"Fabric":"Chiffon","Fit":"A-line","Care":"Hand wash"}'),
  ('00000000-0000-0000-0000-000000000516', 'Bronze Glow Blush Palette', 'bronze-glow-blush-palette',
   'A curated palette of three warm blush and bronze shades.',
   '00000000-0000-0000-0000-000000000417', '00000000-0000-0000-0000-000000000303', 27.99, NULL, 14, 'active', 4.7, 66, 260, 1400, FALSE, FALSE, FALSE, TRUE,
   '{"Shades":"3","Finish":"Satin","Cruelty Free":"Yes"}');

INSERT INTO product_variants (id, product_id, sku, size, color, shade, price, stock_qty) VALUES
  ('00000000-0000-0000-0000-000000000601', '00000000-0000-0000-0000-000000000501', 'QT-501-XS', 'XS', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000602', '00000000-0000-0000-0000-000000000501', 'QT-501-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000603', '00000000-0000-0000-0000-000000000501', 'QT-501-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000604', '00000000-0000-0000-0000-000000000501', 'QT-501-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000605', '00000000-0000-0000-0000-000000000501', 'QT-501-XL', 'XL', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000606', '00000000-0000-0000-0000-000000000502', 'QT-502-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000607', '00000000-0000-0000-0000-000000000502', 'QT-502-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000608', '00000000-0000-0000-0000-000000000502', 'QT-502-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000609', '00000000-0000-0000-0000-000000000502', 'QT-502-XL', 'XL', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000610', '00000000-0000-0000-0000-000000000503', 'QT-503-BLUSH', NULL, 'Blush', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000611', '00000000-0000-0000-0000-000000000503', 'QT-503-PLUM', NULL, 'Plum', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000612', '00000000-0000-0000-0000-000000000503', 'QT-503-GOLD', NULL, 'Gold', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000613', '00000000-0000-0000-0000-000000000503', 'QT-503-IVORY', NULL, 'Ivory', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000614', '00000000-0000-0000-0000-000000000504', 'QT-504-RUBY', NULL, NULL, 'Ruby Red', NULL, 15),
  ('00000000-0000-0000-0000-000000000615', '00000000-0000-0000-0000-000000000504', 'QT-504-MAUVE', NULL, NULL, 'Mauve', NULL, 15),
  ('00000000-0000-0000-0000-000000000616', '00000000-0000-0000-0000-000000000504', 'QT-504-NUDE', NULL, NULL, 'Nude', NULL, 15),
  ('00000000-0000-0000-0000-000000000617', '00000000-0000-0000-0000-000000000504', 'QT-504-BERRY', NULL, NULL, 'Berry', NULL, 15),
  ('00000000-0000-0000-0000-000000000618', '00000000-0000-0000-0000-000000000505', 'QT-505-XS', 'XS', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000619', '00000000-0000-0000-0000-000000000505', 'QT-505-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000620', '00000000-0000-0000-0000-000000000505', 'QT-505-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000621', '00000000-0000-0000-0000-000000000505', 'QT-505-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000622', '00000000-0000-0000-0000-000000000506', 'QT-506-XS', 'XS', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000623', '00000000-0000-0000-0000-000000000506', 'QT-506-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000624', '00000000-0000-0000-0000-000000000506', 'QT-506-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000625', '00000000-0000-0000-0000-000000000506', 'QT-506-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000626', '00000000-0000-0000-0000-000000000506', 'QT-506-XL', 'XL', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000627', '00000000-0000-0000-0000-000000000507', 'QT-507-FAIR', NULL, NULL, 'Fair', NULL, 15),
  ('00000000-0000-0000-0000-000000000628', '00000000-0000-0000-0000-000000000507', 'QT-507-LIGHT', NULL, NULL, 'Light', NULL, 15),
  ('00000000-0000-0000-0000-000000000629', '00000000-0000-0000-0000-000000000507', 'QT-507-MEDIUM', NULL, NULL, 'Medium', NULL, 15),
  ('00000000-0000-0000-0000-000000000630', '00000000-0000-0000-0000-000000000507', 'QT-507-MEDTAN', NULL, NULL, 'Medium Tan', NULL, 15),
  ('00000000-0000-0000-0000-000000000631', '00000000-0000-0000-0000-000000000507', 'QT-507-DEEP', NULL, NULL, 'Deep', NULL, 15),
  ('00000000-0000-0000-0000-000000000632', '00000000-0000-0000-0000-000000000508', 'QT-508-30ML', NULL, NULL, '30 ml', NULL, 12),
  ('00000000-0000-0000-0000-000000000633', '00000000-0000-0000-0000-000000000508', 'QT-508-50ML', NULL, NULL, '50 ml', NULL, 12),
  ('00000000-0000-0000-0000-000000000634', '00000000-0000-0000-0000-000000000509', 'QT-509-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000635', '00000000-0000-0000-0000-000000000509', 'QT-509-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000636', '00000000-0000-0000-0000-000000000509', 'QT-509-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000637', '00000000-0000-0000-0000-000000000510', 'QT-510-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000638', '00000000-0000-0000-0000-000000000510', 'QT-510-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000639', '00000000-0000-0000-0000-000000000510', 'QT-510-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000640', '00000000-0000-0000-0000-000000000510', 'QT-510-XL', 'XL', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000641', '00000000-0000-0000-0000-000000000511', 'QT-511-200ML', NULL, NULL, '200 ml', NULL, 10),
  ('00000000-0000-0000-0000-000000000642', '00000000-0000-0000-0000-000000000512', 'QT-512-GOLD', NULL, 'Gold', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000643', '00000000-0000-0000-0000-000000000512', 'QT-512-SILVER', NULL, 'Silver', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000644', '00000000-0000-0000-0000-000000000512', 'QT-512-ROSE', NULL, 'Rose Gold', NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000645', '00000000-0000-0000-0000-000000000513', 'QT-513-24', '24', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000646', '00000000-0000-0000-0000-000000000513', 'QT-513-26', '26', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000647', '00000000-0000-0000-0000-000000000513', 'QT-513-28', '28', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000648', '00000000-0000-0000-0000-000000000513', 'QT-513-30', '30', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000649', '00000000-0000-0000-0000-000000000513', 'QT-513-32', '32', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000650', '00000000-0000-0000-0000-000000000514', 'QT-514-BLACK', NULL, 'Black', NULL, NULL, 18),
  ('00000000-0000-0000-0000-000000000651', '00000000-0000-0000-0000-000000000514', 'QT-514-BROWN', NULL, 'Brown Black', NULL, NULL, 18),
  ('00000000-0000-0000-0000-000000000652', '00000000-0000-0000-0000-000000000515', 'QT-515-XS', 'XS', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000653', '00000000-0000-0000-0000-000000000515', 'QT-515-S', 'S', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000654', '00000000-0000-0000-0000-000000000515', 'QT-515-M', 'M', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000655', '00000000-0000-0000-0000-000000000515', 'QT-515-L', 'L', NULL, NULL, NULL, 8),
  ('00000000-0000-0000-0000-000000000656', '00000000-0000-0000-0000-000000000516', 'QT-516-WARM', NULL, NULL, 'Warm Sunset', NULL, 14),
  ('00000000-0000-0000-0000-000000000657', '00000000-0000-0000-0000-000000000516', 'QT-516-ROSY', NULL, NULL, 'Rosy Dawn', NULL, 14);

INSERT INTO product_images (id, product_id, url, position, is_primary) VALUES
  ('00000000-0000-0000-0000-000000000801', '00000000-0000-0000-0000-000000000501', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8', 0, TRUE),
  ('00000000-0000-0000-0000-000000000802', '00000000-0000-0000-0000-000000000502', 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea', 0, TRUE),
  ('00000000-0000-0000-0000-000000000803', '00000000-0000-0000-0000-000000000503', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3', 0, TRUE),
  ('00000000-0000-0000-0000-000000000804', '00000000-0000-0000-0000-000000000504', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa', 0, TRUE),
  ('00000000-0000-0000-0000-000000000805', '00000000-0000-0000-0000-000000000505', 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446', 0, TRUE),
  ('00000000-0000-0000-0000-000000000806', '00000000-0000-0000-0000-000000000506', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1', 0, TRUE),
  ('00000000-0000-0000-0000-000000000807', '00000000-0000-0000-0000-000000000507', 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e', 0, TRUE),
  ('00000000-0000-0000-0000-000000000808', '00000000-0000-0000-0000-000000000508', 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be', 0, TRUE),
  ('00000000-0000-0000-0000-000000000809', '00000000-0000-0000-0000-000000000509', 'https://images.unsplash.com/photo-1598554747436-c9293d6a588f', 0, TRUE),
  ('00000000-0000-0000-0000-000000000810', '00000000-0000-0000-0000-000000000510', 'https://images.unsplash.com/photo-1509631179647-0177331693ae', 0, TRUE),
  ('00000000-0000-0000-0000-000000000811', '00000000-0000-0000-0000-000000000511', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9', 0, TRUE),
  ('00000000-0000-0000-0000-000000000812', '00000000-0000-0000-0000-000000000512', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d', 0, TRUE),
  ('00000000-0000-0000-0000-000000000813', '00000000-0000-0000-0000-000000000513', 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246', 0, TRUE),
  ('00000000-0000-0000-0000-000000000814', '00000000-0000-0000-0000-000000000514', 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133', 0, TRUE),
  ('00000000-0000-0000-0000-000000000815', '00000000-0000-0000-0000-000000000515', 'https://images.unsplash.com/photo-1583496661160-fb5886a4686d', 0, TRUE),
  ('00000000-0000-0000-0000-000000000816', '00000000-0000-0000-0000-000000000516', 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9', 0, TRUE);

INSERT INTO promotions (id, code, title, description, type, value, minimum_order_amount, maximum_discount, is_active) VALUES
  ('00000000-0000-0000-0000-000000000701', 'QUEEN10', '10% off your order', 'Get 10% off on orders above KSh 50. Maximum discount KSh 25.', 'percentage', 10, 50, 25, TRUE),
  ('00000000-0000-0000-0000-000000000702', 'ROYAL20', '20% off your order', 'Get 20% off on orders above KSh 100. Maximum discount KSh 60.', 'percentage', 20, 100, 60, TRUE),
  ('00000000-0000-0000-0000-000000000703', 'FLAT15', 'KSh 15 off your order', 'Get KSh 15 off on orders above KSh 75.', 'fixed', 15, 75, NULL, TRUE);

-- ======================= maintenance & consistency ==========================

-- updated_at is maintained automatically on every row change.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_categories_updated_at ON categories;
CREATE TRIGGER trg_categories_updated_at BEFORE UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_brands_updated_at ON brands;
CREATE TRIGGER trg_brands_updated_at BEFORE UPDATE ON brands
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_variants_updated_at ON product_variants;
CREATE TRIGGER trg_variants_updated_at BEFORE UPDATE ON product_variants
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_carts_updated_at ON carts;
CREATE TRIGGER trg_carts_updated_at BEFORE UPDATE ON carts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_cart_items_updated_at ON cart_items;
CREATE TRIGGER trg_cart_items_updated_at BEFORE UPDATE ON cart_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_wishlists_updated_at ON wishlists;
CREATE TRIGGER trg_wishlists_updated_at BEFORE UPDATE ON wishlists
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_addresses_updated_at ON addresses;
CREATE TRIGGER trg_addresses_updated_at BEFORE UPDATE ON addresses
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_promotions_updated_at ON promotions;
CREATE TRIGGER trg_promotions_updated_at BEFORE UPDATE ON promotions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_payments_updated_at ON payments;
CREATE TRIGGER trg_payments_updated_at BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_installments_updated_at ON installments;
CREATE TRIGGER trg_installments_updated_at BEFORE UPDATE ON installments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_reviews_updated_at ON reviews;
CREATE TRIGGER trg_reviews_updated_at BEFORE UPDATE ON reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Keep products.rating / products.review_count in sync with APPROVED reviews,
-- so moderation (approve/reject) is reflected immediately.
CREATE OR REPLACE FUNCTION sync_product_rating() RETURNS trigger AS $$
DECLARE
  pid UUID;
BEGIN
  IF TG_OP = 'DELETE' THEN
    pid = OLD.product_id;
  ELSE
    pid = NEW.product_id;
  END IF;
  UPDATE products p
  SET rating = COALESCE(
        (SELECT round(avg(r.rating)::numeric, 2) FROM reviews r
          WHERE r.product_id = pid AND r.is_approved),
        0::numeric
      ),
      review_count = (SELECT count(*) FROM reviews r
          WHERE r.product_id = pid AND r.is_approved)
  WHERE p.id = pid;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_product_rating ON reviews;
CREATE TRIGGER trg_sync_product_rating
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW EXECUTE FUNCTION sync_product_rating();